# Remove URL for GitHub Pages plugin
url: https://jekyll-theme-emojification.michaelnordmeyer.com
# baseurl: "" # The subpath of the site, e.g. /blog
title: Jekyll Theme Emojification
# Description is used for meta headers and feeds. Limit to 160 characters, if possible
description: >-
  A simple and minimal single-author theme with configurable big emoji as the header link, and configurable background colors, which can be chosen for each post or page

## Jekyll build settings https://jekyllrb.com/docs/configuration/default/
exclude: [CODE_OF_CONDUCT.md, jekyll-theme-emojification*, LICENSE, Rakefile.rb, README.md, repo-cards, TODO.md]
ignore_theme_config: true # Since Jekyll 4.0, see: https://jekyllrb.com/docs/themes/#pre-configuring-theme-gems40, https://jekyllrb.com/docs/configuration/options/
kramdown:
  show_warnings: true
  syntax_highlighter_opts:
    disable: true
liquid:
  # Configure Liquid’s parser
  error_mode: strict # default: warn
  # Configure Liquid’s renderer
  strict_filters: true # default: false
  # strict_variables: true # default: false
sass:
  style: compressed
strict_front_matter: true # default: false
# remote_theme: michaelnordmeyer/jekyll-theme-emojification
theme: jekyll-theme-emojification
timezone: Europe/Berlin # default: local timezone

## Custom settings used by plugins and the theme
author:
  name: Michael Nordmeyer
  # email: xxx@example.com
  uri: https://michaelnordmeyer.com/
  copyright: Copyright © Michael Nordmeyer
  license_link: https://raw.githubusercontent.com/michaelnordmeyer/jekyll-theme-emojification/main/LICENSE
# date_format: "%b %-d, %Y" # default: "%Y-%m-%d"
lang: en-US # default: en
# minify: true # default: false (jekyll-feed, jekyll-sitemap)
# Social links are used in SEO meta headers
social:
  fediverse_creator: "@mnordmeyer@indieweb.social" # "@username@fediverse.example"
  links: # The first link will become the webmention `authn`
    - https://github.com/michaelnordmeyer
    - https://www.linkedin.com/in/michaelnordmeyer
    - https://www.xing.com/profile/Michael_Nordmeyer
    - https://indieweb.social/@mnordmeyer
title_separator: " • " # default: " | "
## Custom theme settings
favicon: /assets/icons/yellowgreen.webp # optional, is used by feeds as fallback and sitemap
## Custom theme settings to not overwrite anything from Jekyll or plugins
theme_settings:
  # category_title_prefix: "" # default: "Category: "
  category_feed_all_name: "All" # (mandatory, but can be "")
  # feed_filename: "feed.xml" # default: "feed.xml"
  icon: 🌳
  # redirect_page_title: "Redirecting…" # default: "Redirecting…"
  # redirect_page_from: "Redirecting from" # default: "Redirecting from"
  # redirect_page_to: "to" # default: "to"
  # redirect_page_text: "Click here if you are not being redirected." # default: "Click here if you are not being redirected.""
  # show_descriptions is used to enable descriptions on posts, pages, and index pages like home and categories
  show_descriptions: true # default: false
  theme_color: yellowgreen # default: none (= no colors. If this CSS file is missing, there will be also no structural styling)
  webmention_url: https://webmention.io/jekyll-theme-emojification.michaelnordmeyer.com/webmention

## Plugin settings jekyll-feed (built-in)
feed:
  # excerpt_only: true # default: false (can be declard in front matter as well)
  hide_generator: true # default: false
  icon: /assets/icons/yellowgreen.webp # optional, default: site.favicon
  path: /feed.xml # default: /feed.xml (mandatory)
  # path_xslt: /feed.xslt.xml # default: /feed.xslt.xml
  posts_limit: 1000 # default: 10
  title_separator: ": "

## Plugin settings jekyll-seo-tag (built-in)

## https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Only works for all posts, but can work for a subset of pages
defaults:
  - scope:
      path: "" # an empty string here means all files in the project (allows globs, but is slow)
      type: posts # type (optional): posts, pages, drafts, or any collection
    values:
      layout: post
  - scope:
      path: ""
      type: pages # pages have permalink: /:path/:basename
    values:
      layout: page
      permalink: /:path/:basename
  - scope:
      path: colors/_posts
    values:
      sitemap: false
  - scope:
      path: error
      type: pages
    values:
      icon: 😩
      layout: error
      permalink: /:path/:basename
      sitemap: false
  - scope:
      path: "**/feed.xml"
      type: pages
    values:
      layout: feed-xml
      permalink: /:path/:basename:output_ext
      sitemap: false
  - scope:
      path: defaults-test
      type: pages
    values:
      description: "A quick test to test _config.yml defaults."
      icon: 🪽
      layout: page
      sitemap: false
      theme_color: dodgerblue
  - scope:
      path: ""
    values:
      layout: default
